# Configuración de la base de datos MongoDB
mongo:
  host: 127.0.0.1
  port: 27017
  database: microservice

# Configuración de la base de datos ElephantSQL
postgres:
  host: mahmud.db.elephantsql.com
  port: 5432
  database: iblrcnaa
  username: iblrcnaa
  password: NzSFyMEaa2hAOZ1NJxizLJjXNR8r8pz6


